# Generated by Django 3.2.13 on 2022-06-15 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20220608_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='recipe',
            name='excerpt',
            field=models.TextField(blank=True),
        ),
    ]
