# Generated by Django 3.2.13 on 2022-06-15 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20220615_1229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='content',
        ),
    ]
